apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jenkins
  namespace: default
  labels:
    app: test-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-jenkins
  template:
    metadata:
      labels:
        app: test-jenkins
    spec:
      containers:
      - name: test-jenkins
      image: hayder69/test-jenkins:latest
      ports:
      - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: test-jenkins
  namespace: default
spec:
  selector:
    app: test-jenkins
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8000
